disabled_rules:
    - trailing_whitespace
    - function_body_length
    - line_length
    - orphaned_doc_comment
    - nesting

opt_in_rules:
    - let_var_whitespace

excluded:
    - BoxOffice/AppDelegate.swift
    - BoxOffice/SceneDelegate.swift
    
file_length:
    warning: 400
    error: 500

type_name:
    min_length: 2
    
identifier_name:
    min_length: 2

force_cast: warning
