disabled_rules:
    - trailing_whitespace
    - function_body_length
    - line_length
    - orphaned_doc_comment
    - nesting
    - todo
    - attributes
    
opt_in_rules:
    - let_var_whitespace
    - closure_spacing
    
analyzer_rules:
    - unused_import

excluded:
    - BoxOffice/App/AppDelegate.swift
    - BoxOffice/App/SceneDelegate.swift
    - BoxOfficeTests

file_length:
    warning: 200
    error: 300

type_name:
    min_length: 2
    
identifier_name:
    min_length: 2

force_cast: warning
